// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"food-recipes-backend/global"
	"food-recipes-backend/internal/controller"
	"food-recipes-backend/internal/repo"
	"food-recipes-backend/internal/services"
)

// Injectors from admin.wire.go:

func InitAdminRouterHandler() (*controller.AdminController, error) {
	db := global.ProvideDB()
	iUserRepository := repo.NewUserRepository(db)
	iKeyRepository := repo.NewKeyRepository(db)
	iUserService := services.NewUserService(iUserRepository, iKeyRepository)
	client := global.ProvideRedis()
	adminController := controller.NewAdminController(iUserService, client)
	return adminController, nil
}

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controller.UserController, error) {
	db := global.ProvideDB()
	iUserRepository := repo.NewUserRepository(db)
	iKeyRepository := repo.NewKeyRepository(db)
	iUserService := services.NewUserService(iUserRepository, iKeyRepository)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
