// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"food-recipes-backend/internal/controller"
	"food-recipes-backend/internal/repo"
	"food-recipes-backend/internal/services"
)

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controller.UserController, error) {
	iUserRepository := repo.NewUserRepository()
	iUserService := services.NewUserService(iUserRepository)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
